apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-server
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: books-server
            port:
              number: 8080
